<div class="page-header">
    <h1 class="entry-title">Sistem Pakar</h1>
</div>
<div class="col-sm-12">
    <p class="entry-summary hidden">Sistem pakar metode Teorema Bayes berbasis web dengan PHP dan MySQL. Studi kasus: mendiagnosa Gangguan Menstruasi</p>
    <pre class="entry-content center">Kelainan menstruasi merupakan salah satu kondisi yang paling banyak membuat para perempuan datang berkonsultasi ke dokter spesialis[1], [2]. Dari hasil diskusi dengan salah satu pakar hormonal perempuan, dr. I Putu Gde Wardhiana Sp.OG (K) beliau mengatakan bahwa banyak perempuan yang datang ke tempat praktek beliau mengeluhkan mengenai gangguan/kelainan menstruasi tiap harinya, pasien yang datang didominasi oleh kalangan remaja keatas. Keluhan terbanyak dari kalangan usia ini adalah siklus menstruasi yang tidak teratur, tidak menstruasi dalam jangka waktu lama, menstruasi yang memanjang (lebih dari 8 hari), bahkan terkadang menstruasi sangat banyak sehingga menderita anemia dan harus dirawat serta diberikan transfusi. Pola menstruasi remaja, terutama 3-5 tahun sejak menstruasi pertama kalinya (menars) sangat berbeda dengan pola haid wanita dewasa. Penelitian tentang (Manajemen Kesehatan Menstruasi) MKM, khususnya pada remaja putri di indonesia masih terbatas akan pengetahuan tentang Menstruasi[3].
    Masalah yang dihadapi oleh masyarakat untuk pergi ke dokter adalah kebanyakan perempuan masih malu dan merasa tidak perlu berkonsultasi kedokter spesialis kandungan. Selain itu adalah keterbatasan tenaga, biaya yang cukup mahal, kesibukan pribadi, jarak lokasi yang jauh, dan juga jalanan yang macet[4]. Perkembangan teknologi yang sangat pesat dapat membantu di segala bidang, salah satunya adalah bidang kedokteran. Alternatif selain pergi ke dokter untuk mendiagnosa kelainan menstruasi pada perempuan adalah menggunakan sistem pakar[5]. 
    Sistem pakar (Expert system) merupakan salah satu bagian dari kecerdasan buatan (Artificial Intelligence). Ilmu kecerdasan buatan mempelajari tentang bagaimana cara agar mesin dapat bekerja dan memiliki kemampuan seperti manusia, mulai dari meniru cara otak manusia bekerja, meniru jaringan saraf, kemampuan melihat, berkomunikasi, bergerak serta mengenali sesuatu dan bahkan berkembang ke arah yang menyangkut tentang psikologi dan kesehatan[6], [7]. Sistem pakar tidak berarti menggantikan peran manusia dalam pengambilan keputusan, tetapi bertujuan untuk membantu aktivitas para pakar sebagai asisten yang cerdas sebagai diagnosa/anamnesa awal[7].
    Berdasarkan uraian permasalahan tersebut, maka dalam penelitian ini akan dibangun suatu sistem pakar untuk mendiagnosis kelainan/gangguan menstruasi yang berbasis Website menggunakan mesin inferensi dengan metode Decision Tree. Metode tersebut merupakan salah satu algoritma (Pembelajaran Mesin) Machine Learning yang bekerja mirip dengan cara manusia mengambil keputusan. Algoritma akan membentuk flow chart pohon terbalik, dimana akarnya (root) berada diatas sedangkan cabang dan daun (leaf) berada dibawah[8]. Penerapan sistem pakar diterapkan kedalam sistem berbasis Web. Diharapkan dengan sistem pakar berbasis Website ini dapat membantu masyarakat untuk mendiagnosis awal kelainan menstruasi pada wanita sebelum dibawa ke dokter spesialis.
    </pre>
</div>